#библиотеки стикеров
welcome_stickers_id = ['CAACAgIAAxkBAAJAJ1-Y7xYeCFw7W1d1NTDPSbWFqKJgAAJ0AAM7YCQUs8te1W3kR_QbBA',
                       'CAACAgIAAxkBAAJAKl-Y7zFxon611n7irTqF9ppIJzI_AAL1AwACRxVoCYDkI4apaTHtGwQ',
                       'CAACAgIAAxkBAAJALV-Y709SS_NbyoBfTC8BOop4GJySAAJOAgACel9AC_2AVZz45IeJGwQ',
                       'CAACAgIAAxkBAAJAM1-Y72Zyac3q-uyMFLMIkqiPZd2cAALkAAOWn4wOxwgM9TN-1vcbBA',
                       'CAACAgIAAxkBAAJAMF-Y72V1A2xY3Aj9V2GMfV-ZYDr8AAKHAgACVp29CkLtdCtAV9CQGwQ'
                       ]

stickers_id = ['CAACAgIAAxkBAAJANl-Y75YQ8pGWtBipNGYpjGqrfbUgAAJaAAM_W6Y7v9jKOFYpupYbBA',
               'CAACAgEAAxkBAAJAOV-Y75euhdoT5NCZ-THhr9rPvxfzAALBAAP27y4t7kciaRUJBTQbBA',
               'CAACAgIAAxkBAAJAPF-Y75jt3dFep2Q5grddgYHl70jZAAKGAgACVp29CurmC5LHcbYBGwQ',
               'CAACAgIAAxkBAAJAP1-Y75rMlvfFQfvO7rs37-IQU3qDAAKaAAMw1J0R-btImmvuDbMbBA',
               'CAACAgIAAxkBAAJAQl-Y75rR7RGcoDN7p2oUdahYKIVFAAIHBAACRxVoCU5aoy0hvrnIGwQ',
               'CAACAgEAAxkBAAJARV-Y75tLUpFcBUy4LuhOBji_lF37AAISAAP27y4togq5RPoXHUIbBA',
               'CAACAgIAAxkBAAJASF-Y75wau8s-8VdrazQRBTpI3p6OAAKPEQACPLPFBzLcyrxNSGysGwQ',
               'CAACAgIAAxkBAAJAS1-Y76IEqlJ3DZrBNMcn8AWQOYU8AALRAQACPQ3oBPCyBQkFuchBGwQ',
               'CAACAgIAAxkBAAJATl-Y76MOdsCnkFIAAZZQuIbAmN-rWwACngAD9wLIDxjzyiQZP6pbGwQ',
               'CAACAgIAAxkBAAJAUV-Y76kaZUR7R4aO32CWJm8G_CZCAAIyAAMWQmsKn00v9tKrWXkbBA',
               'CAACAgIAAxkBAAJAVF-Y76ojVliBi2M7xsnGjjkGVTuGAAJQAQACzcBIGNnToTej4DmQGwQ',
               'CAACAgEAAxkBAAJAV1-Y8DOsNvEAAe-RHczZdZ7dMsLmXwACDAAD9u8uLaQAATQ2tFWAcRsE'
               ]

